name: Prepare

inputs:
  apt-cache-key:
    type: string

runs:
  using: composite
  steps:
    - run: git fetch --depth=200 --tags
      shell: bash

    - run: git submodule update --init
      shell: bash

    - uses: actions/cache@v2
      with:
        path: |
          /var/cache/apt/*.bin
          /var/cache/apt/archives/*.deb
        key: ${{ inputs.apt-cache-key }}-apt-${{ hashFiles('**/*.sh') }}
        restore-keys: ${{ inputs.apt-cache-key }}-apt-
      if: ${{ inputs.apt-cache-key }}
