name: Build - Odroid

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{ github.ref }}-odroid
  cancel-in-progress: true

env:
  QT_VERSION: "5.15.2"


jobs:
  odroid:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        model: [c1, c2, xu3]
    env:
      QT_TARGET: odroid-${{ matrix.model }}-static
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 200
      - uses: ./.github/actions/pegasus-prepare
        with:
          apt-cache-key: odroid-${{ matrix.model }}

      - run: sudo -E ./.ci/install_deps.sh
      - run: ./.ci/build.sh
      - run: ./.ci/create_release.sh

      - uses: actions/upload-artifact@v2
        with:
          name: odroid-${{ matrix.model }}-static
          path: deploy/*.zip

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: mmatyas/pegasus-deploy-staging
          personal_token: ${{ secrets.PEGASUS_GHACTIONS_TOKEN }}
          publish_branch: continuous-odroid-${{ matrix.model }}-static
          publish_dir: ./deploy
          force_orphan: true
