name: Build - MacOS

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{ github.ref }}-mac
  cancel-in-progress: true

env:
  QT_VERSION: "5.15.2"
  SDL_VERSION: "2.0.18"


jobs:
  macos-static:
    runs-on: macos-10.15
    env:
      QT_TARGET: macos-static
      SDL_TARGET: macos
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 200
      - run: git fetch --tags

      - run: sudo -E ./.ci/install_deps.sh
      - run: ./.ci/build.sh --with-tests
      - run: ./.ci/create_release.sh

      - uses: actions/upload-artifact@v2
        with:
          name: macos-static
          path: deploy/*.zip
