name: Build - X11

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{ github.ref }}-x11
  cancel-in-progress: true

env:
  QT_VERSION: "5.15.2"
  SDL_VERSION: "2.0.18"


jobs:
  x11-qmake:
    runs-on: ubuntu-18.04
    env:
      QT_TARGET: x11-static
      SDL_TARGET: x11-bionic
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 200
      - uses: ./.github/actions/pegasus-prepare
        with:
          apt-cache-key: x11-qmake

      - run: sudo -E ./.ci/install_deps.sh
      - run: ./.ci/build.sh --with-tests

      - name: Create DEB
        run: |
          export PATH="$PATH:/home/runner/.gem/ruby/2.5.0/bin"
          gem install --user-install -N fpm -v 1.10.2
          ./.ci/x11_create_deb.sh
      - run: ./.ci/create_release.sh

      - uses: actions/upload-artifact@v2
        with:
          name: x11-static
          path: |
            deploy/*.zip
            deploy/*.deb

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: mmatyas/pegasus-deploy-staging
          personal_token: ${{ secrets.PEGASUS_GHACTIONS_TOKEN }}
          publish_branch: continuous-x11-static
          publish_dir: ./deploy
          force_orphan: true

  x11-cmake:
    runs-on: ubuntu-18.04
    env:
      QT_TARGET: x11-static
      SDL_TARGET: x11-bionic
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 200
      - uses: ./.github/actions/pegasus-prepare
        with:
          apt-cache-key: x11-cmake

      - run: sudo -E ./.ci/install_deps.sh --cmake
      - run: ./.ci/build.sh --cmake --with-tests
      - run: ./.ci/create_release.sh

      - uses: actions/upload-artifact@v2
        with:
          name: x11-static_cmake
          path: deploy/*.zip
