name: Build - Raspberry Pi

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{ github.ref }}-rpi
  cancel-in-progress: true

env:
  QT_VERSION: "5.15.2"
  SDL_VERSION: "2.0.18"


jobs:
  raspberry:
    runs-on: ubuntu-latest
    container: mmatyas/pegasus-qt_raspberry-gha
    strategy:
      matrix:
        include:
          - pi: rpi1
            sdl: brcm
          - pi: rpi2
            sdl: brcm
          - pi: rpi3
            sdl: brcm
          - pi: rpi4
            sdl: mesa
    env:
      QT_TARGET: ${{ matrix.pi }}-static
      SDL_TARGET: rpi-${{ matrix.sdl }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pegasus-prepare
        with:
          apt-cache-key: ${{ matrix.pi }}

      - run: ./.ci/install_deps.sh
      - run: ./.ci/build.sh
      - run: ./.ci/create_release.sh

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.pi }}-static
          path: deploy/*.zip

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: mmatyas/pegasus-deploy-staging
          personal_token: ${{ secrets.PEGASUS_GHACTIONS_TOKEN }}
          publish_branch: continuous-${{ matrix.pi }}-static
          publish_dir: ./deploy
          force_orphan: true
